#!/usr/bin/env python3
from sys import argv;P=argv[1:] if argv[1:] else input().split();q="'";Q='"'
try: print(*[chr(int(i.replace("U+",''),16)) for i in P], sep='')
except ValueError as E: print(f"Error: {E.__reduce__()[1][0].split(': ')[1].replace(q,Q)} is pretty sus")
